# -*- coding: utf-8 -*-
"""Scraping _Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQi1cReKUnhb-RnSKgAwn8cdR3aCU4kq
"""

import requests

r=requests.get('https://www.nytimes.com/interactive/2017/06/23/opinion/trumps-lies.html')

print(r.text)

from bs4 import BeautifulSoup

soup=BeautifulSoup(r.text,'html.parser')

soup.a

results=soup.find_all('span',attrs={'class':'short-desc'})

len(result)

result[0:3]

result[-1]

first_result=results[0]

first_result.find('strong')

text=first_result.find('strong').text[0:-1]

text

text+', 2017'

first_result.contents

first_result.contents[0].text[0:-1]

first_result.contents[1][1:-2]

first_result.contents[2].text[1:-1]

first_result.contents[2]

first_result.contents[2].find('a')['href']

first_result.find('a')

first_result.find('a').text[1:-1]

first_result.find('a')['href']

records=[]
for result in results:
  date=result.contents[0].text[0:-1]+' 2017'
  lie=result.contents[1][0:-2]
  explanation=result.contents[2].text[1:-1]
  url=result.find('a')['href']
  records.append((date, lie, explanation, url))

len(records)

records[0:3]

